### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [inetic/club#1]
I would like to point out that identifiers like "[`__BINARY_DECODER_H__`](https://github.com/inetic/club/blob/b542772f88d5030c575c4165f92ca4a8561c942e/include/binary/decoder.h#L15)" and "[`__CLUB_HUB_H__`](https://github.com/inetic/club/blob/5774ae3109c08b581fbe71932f3bd13eda4bd8ba/include/club/hub.h#L15)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by inetic** [comment]
Aha, I wasn't aware of that. Thanks. Yes, if you're up for it, I would be grateful. Note though that I've recently started to use `#pragma once`. I've done it mostly due to laziness as it's a bit more practical, feel free to change that too.

**Comment by inetic** [comment]
Fixed [here](https://github.com/inetic/club/commit/d6662b2feb6e12c757def8e0c08b6f97a88c68c4)

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/inetic/club/commit/d6662b2feb6e12c757def8e0c08b6f97a88c68c4 "Deletion of some underscores").
